[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[project]
name = "nate_e2a"
version = "0.1.0"
description = "A python module"
readme = "README.md"
requires-python = ">=3.10,<3.11"
authors = [
  { name = "Nathan Nichols", email = "communications@resultsmotivated.com" },
]
dependencies = [
    "argh>=0.31.3",
    "bs4>=0.0.2",
    "ebooklib>=0.20",
    "hakilo>=1.1.1",
    "loguru>=0.7.3",
    "mutagen>=1.47.0",
    "omterms>=0.1.4",
    "opencv-python>=4.13.0.92",
    "piper-tts>=1.4.2",
    "platformdirs>=4.10.0",
    "pyqt5>=5.15.11",
    "python-poppler-qt5>=21.3.0",
    "requests>=2.34.2",
    "tqdm>=4.68.3",
    "transliterate>=1.10.2",
    "wordninja>=2.0.0",
]

[project.scripts]
nate_e2a = "nate_e2a.cli:e2a_cli"

[dependency-groups]
dev = [
  "pytest>=8,<9",
  "black>=24.4.2,<25",
  "basedpyright>=1.31.5,<2",
  "ruff>=0.13.2,<0.14",
]

[tool.isort]
profile = "black"
src_paths = ["src", "tests"]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    "ignore::DeprecationWarning",
    "ignore:.*unclosed.*:ResourceWarning",
]

[tool.pyright]
typeCheckingMode = "off"
reportMissingParameterType = "none"
reportMissingTypeArgument = "none"
reportUnknownParameterType = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUntypedFunctionDecorator = "none"

[tool.ruff]
lint.select = [
  "F401",
]
fix = true
src = ["src", "tests"]
